resources:
  - ../../base/istory-app

namespace: istory-prod

patches:
  - path: patch-lb-annotations.yml
    target:
      kind: Service
      name: istory-app-lb
  - path: patch-deploy.yml
    target:
      kind: Deployment
      name: istory-app-deploy

images:
  - name: dangtong76/istory
    newTag: latest

configMapGenerator:
  - name: istory-app-config
    behavior: replace
    envs:
      - .env.app.config

secretGenerator:
  - name: istory-db-secret
    envs:
      - .env.db.secret
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true